# Theme
theme = Ayu Mirage
font-family = Liga Share Tech Mono
font-size = 22
# font-feature = zero

# Background
background-opacity = 0.95

# Window
window-width = 100
window-height = 26
window-padding-x = 8
adjust-cell-height = 8
keybind = shift+enter=text:\n
