# Theme
theme = Raycast Dark
font-family = Liga Paper Mono
font-size = 20
# font-feature = zero

# Background
background-opacity = 0.95

# Window
window-width = 100
window-height = 26
window-padding-x = 8
adjust-cell-height = 8
keybind = shift+enter=text:\n
